// <auto-generated />
namespace Appointment_Scheduler.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DeletingDataEnd_AddingHours : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DeletingDataEnd_AddingHours));
        
        string IMigrationMetadata.Id
        {
            get { return "202209191125438_DeletingDataEnd_AddingHours"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
